language: rust
# sudo is required to enable kcov to use the personality syscall
sudo: required

before_script:
  - eval git pull --rebase https://github.com/eldruin/ads1x1x-rs master
  - eval git log --pretty=oneline HEAD~5..HEAD
  - export PATH=$HOME/.cargo/bin:$PATH

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu

    - env: TARGET=x86_64-unknown-linux-gnu COVERAGE=1 LLVM_CONFIG=llvm-config-7
      rust: nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-7-dev

    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly

    # Raspberry Pi 1
    - env: TARGET=arm-unknown-linux-gnueabi DISABLE_EXAMPLES=1 DISABLE_TESTS=1
      rust: nightly

    # Raspberry Pi 2, 3, etc
    - env: TARGET=armv7-unknown-linux-gnueabihf DISABLE_EXAMPLES=1 DISABLE_TESTS=1
      rust: nightly

    # Bare metal
    - env: TARGET=thumbv6m-none-eabi
      rust: beta
    - env: TARGET=thumbv7em-none-eabi
      rust: beta
    - env: TARGET=thumbv7em-none-eabihf
      rust: beta
    - env: TARGET=thumbv7m-none-eabi
      rust: beta

before_install:
  - set -e
  - rustup self update

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo
cache:
  directories:
    - /home/travis/.cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo
  - rm -rf /home/travis/.cargo/registry

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
